apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: airflow-secrets
  namespace: platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: airflow-secrets
    creationPolicy: Owner
  data:
    - secretKey: AIRFLOW__CORE__FERNET_KEY
      remoteRef:
        key: "airflow/dev/fernet_key"
    - secretKey: AIRFLOW__WEBSERVER__SECRET_KEY
      remoteRef:
        key: "airflow/dev/webserver_secret_key"
    - secretKey: AIRFLOW__CONN_REDSHIFT
      remoteRef:
        key: "airflow/dev/redshift_creds"
