apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  source:
    repoURL: "https://github.com/KarthikKunchala23/platform.git"
    targetRevision: main
    path: charts/airflow   # point to your chart values or helm chart wrapper in repo
    helm:
      valueFiles:
        - ../../charts-values/values-k8s-exec.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
