apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-load-balancer-controller
  namespace: argocd
spec:
  source:
    repoURL: "https://aws.github.io/eks-charts"
    chart: aws-load-balancer-controller
    targetRevision: "1.13.4"
    helm:
      values: |
        clusterName: "<your-cluster-name>"    # replace after terraform outputs
        region: "us-east-1"
        vpcId: "<VPC_ID>"                     # replace or use k8s templating
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
