name: Deploy Platform Apps via ArgoCD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Application to be deployed(argocd, airflow, alb-controller)"
        required: true
        default: "dev"
        type: choice
        options:
            - argocd
            - airflow
            - alb-controller
  push:
    branches:
      - main

jobs:
  deploy-platform:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout infra repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name data-plat-eks-dev --region ${{ env.AWS_REGION }}

      - name: Ensure ArgoCD namespace exists
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply all ArgoCD Projects & Applications
        run: |
          kubectl apply -n argocd -R -f ${{ github.workspace }}/apps/{{ github.event.inputs.environment }}/

      - name: Wait for ArgoCD Server
        run: |
          kubectl rollout status deployment/argocd-server -n argocd --timeout=300s || true
