name: Bootstrap ArgoCD

on:
  workflow_dispatch:

jobs:
  bootstrap-argocd:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.29.0'

      - name: Update kubeconfig for EKS
        run: |
          aws eks update-kubeconfig --name data-plat-eks-dev --region ${{ env.AWS_REGION }}

      - name: Create ArgoCD namespace
        run: |
          kubectl create namespace argocd --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply ArgoCD Application CR (points to argocd-helm repo)
        run: |
          kubectl apply -n argocd -R -f ${{ github.workspace }}/apps/argocd/applications/

      - name: Wait for ArgoCD to bootstrap itself
        run: |
          echo "Waiting for ArgoCD pods..."
          kubectl rollout status deployment/argocd-server -n argocd --timeout=300s || true
          kubectl rollout status deployment/argocd-repo-server -n argocd --timeout=300s || true
          kubectl rollout status deployment/argocd-application-controller -n argocd --timeout=300s || true
